PSR-192
Sage-Bionetworks/Psorcast-iOS pull request #150
Opened 2021-02-22 01:25 UTC by dephillipsmichael

Added phone based sign in based on mPower 2.  This supports using the phone code token that was sent to your mobile phone, so it even works on simulator.

I moved externalID sign in over to long-holding the welcome screen video, if you still want to use that.  It only works like that for DEBUG builds.

2021-02-22 14:27 UTC, DanWebster commented on Psorcast/Psorcast/Base.lproj/PhoneSignIn.json
> +                "text":"Please enter your phone number so we can see if you have an existing account.\n\nWe will not use your phone number for anything else until you have completed the Consent step
```suggestion
                "text":"Please enter your phone number to create and verify your account with a text message.\n\nWe will NEVER sell, rent, or lease your contact information.",
```

2021-02-22 14:28 UTC, DanWebster commented on Psorcast/Psorcast/Base.lproj/PhoneSignIn.json
> +                 "title":"Your registration link is on its way!",
```suggestion
                 "title":"Your sign-up link is on its way!",
```

2021-02-22 14:30 UTC, DanWebster requested changes
The 'Learn More' link on the first screen gets you out to a page that you can't 'X' out of or return from (screenshot)
![IMG_AB243D87406B-1](https://user-images.githubusercontent.com/3682103/108720101-40443500-74d5-11eb-873b-f1effbcff0ab.jpeg).

I got a verify and a sign-in code at the same time (screenshot).  Is this the expected functionality?  I tried putting in the second of these, but it hung the app (screenshot)

![IMG_55AA166D86E6-1](https://user-images.githubusercontent.com/3682103/108720714-058ecc80-74d6-11eb-99d2-889fdc4ae48b.jpeg)
![IMG_A1044528AD8F-1](https://user-images.githubusercontent.com/3682103/108720719-07589000-74d6-11eb-8241-303b09641df1.jpeg)

Added in in-line text changes for this PR in terms of language on the screen

2021-02-22 16:41 UTC, dephillipsmichael commented
@DanWebster the learn more link is launched by BridgeApp SDK, so I'll have to check with Shannon on that one.

2021-02-23 22:44 UTC, dephillipsmichael commented
@DanWebster this should be fixed to include all your changes, as well as fixing the sign up / sign in flow.  I believe you will still get 2 tokens from using sign up flow, but the first one should be valid.  Sign in flow seems to only send 1 token correctly.  I will keep trying to fix the 2 tokens issue with Alx.

2021-02-24 15:57 UTC, DanWebster commented
@dephillipsmichael I am able to sign in now (with an existing account) and the 'learn more' is dismissable with a downward swipe now too.  Will merge and create story for troubleshooting the double text once I repro after deleting my account in Bridge Study manager

2021-02-24 15:57 UTC, merged