PSR 238
Sage-Bionetworks/Psorcast-iOS pull request #162
Opened 2021-04-12 08:08 UTC by EricSiegNW

add some detail text handling for insights and withdraw profile items

2021-04-12 08:08 UTC, EricSiegNW commented on Psorcast/Psorcast/PopTip/PopTipController.swift
> -                // scrollview offset y
cleanup

2021-04-12 08:09 UTC, EricSiegNW commented
Most of the work is done by adjusting the profile data source json in bridge, this just adds some profile item handling to add detail text for withdraw (not enrolled NYI) and Insights

2021-04-12 08:14 UTC, EricSiegNW commented on Psorcast/Psorcast/ProfileTabViewController.swift
> +        // Todo: add logic to determine if enrolled, adjust return values here appropriately
Would they make it to this screen without being enrolled?

2021-04-12 17:24 UTC, DanWebster requested changes
@EricSiegNW I couldn't find the strings in Psorcast.strings or in the profile view controller to be able to make a quick committable change here; perhaps this is specified in the storyboard? Could you change the tableviewcell title text for the 'Health Information' section to be the following:
Psoriasis diagnosis -> Diagnoses
Psoriasis Symptoms -> Current Symptoms

2021-04-12 17:24 UTC, DanWebster commented on Psorcast/Psorcast/ProfileTabViewController.swift
> +        // Todo: add logic to determine if enrolled, adjust return values here appropriately
@EricSiegNW good question, which I think the answer is no.  Still, it doesn't hurt to have this little reminder that you are in a research study currently

2021-04-13 18:36 UTC, DanWebster approved these changes

2021-04-13 18:37 UTC, merged