Psr 437 438
Sage-Bionetworks/Psorcast-iOS pull request #189
Opened 2021-08-02 04:20 UTC by EricSiegNW

Subclass Instruction text, center the title text, adjust image height for the instruction steps to always be the same.

2021-08-02 17:20 UTC, dephillipsmichael commented on Psorcast/Psorcast/Base.lproj/Main.storyboard
> +                                                                                <rect key="frame" x="32" y="248" width="317" height="52"/>
This doesn't seem related to this PR, is it?

2021-08-02 17:25 UTC, dephillipsmichael requested changes
I'm not sure we want to point SageResearch at your fork's branch.  So holding off on approving this.

An easier route would be to just make your own xib for the OnboardingInstructionViewController, because even if you merge into SageResearch, you will have to back-version the spot and have Carthage and all the other sub-modules now point at that new version.

2021-08-02 22:38 UTC, EricSiegNW commented
> I'm not sure we want to point SageResearch at your fork's branch. So holding off on approving this.
> 
> An easier route would be to just make your own xib for the OnboardingInstructionViewController, because even if you merge into SageResearch, you will have to back-version the spot and have Carthage and all the other sub-modules now point at that new version.

Why can't we just merge into SageResearch and point it at the latest? The only changes SageResearch since our old head are a 2 line change by Shannon related to a voicebox thing which seems fine to pull in and you making a similar change a month ago to expose an internal function in the RSDStepViewController.

Seems like we can merge into SageResearch, point at latest, the end, rather than duplicating an existing class and Xib.

2021-08-02 22:40 UTC, EricSiegNW commented
There's also definitely a weird situation where our project points at an almost modern version of SageResearch but MotorControl appears to point at a 2019 version.

2021-08-02 22:58 UTC, dephillipsmichael commented
> > I'm not sure we want to point SageResearch at your fork's branch. So holding off on approving this.
> > An easier route would be to just make your own xib for the OnboardingInstructionViewController, because even if you merge into SageResearch, you will have to back-version the spot and have Carthage and all the other sub-modules now point at that new version.
> 
> Why can't we just merge into SageResearch and point it at the latest? The only changes SageResearch since our old head are a 2 line change by Shannon related to a voicebox thing which seems fine to pull in and you making a similar change a month ago to expose an internal function in the RSDStepViewController.
> 
> Seems like we can merge into SageResearch, point at latest, the end, rather than duplicating an existing class and Xib.

You're most likely right that it can be done.  I'm jaded from all my time wasted on messing with that stuff, go for it.  I'll remove my review.

2021-08-05 10:58 UTC, DanWebster commented
@EricSiegNW Is this ready to merge now, or should we wait on pending Sage Research changes?

2021-08-16 03:36 UTC, DanWebster approved these changes

2021-08-16 03:36 UTC, merged