Psr 457
Sage-Bionetworks/Psorcast-iOS pull request #210
Opened 2021-10-03 14:13 UTC by EricSiegNW

Adds the new progress Bar w/ mask to break it up into 12 chunks
Updates Insight Panel
New puzzle piece/selected puzzle piece

2021-10-03 20:58 UTC, dephillipsmichael commented
I'm glad to see the progress bar mask solution worked out!

I did notice that the quality is blurry on a 3x device:
<img width="334" alt="Screen Shot 2021-10-17 at 1 54 40 PM" src="https://user-images.githubusercontent.com/5590748/135771337-c92c99d6-b47e-46b1-b365-2eff471292dd.png">

Then I checked the assets, and you missed 1x and 3x
<img width="815" alt="Screen Shot 2021-10-03 at 1 55 33 PM" src="https://user-images.githubusercontent.com/5590748/135771351-ea5281cf-6485-403e-982d-76c4134ef4f6.png">

2021-10-03 20:59 UTC, dephillipsmichael commented on Psorcast/Psorcast/MeasureTabViewController.swift
> +    let totalStudyWeeks = 12
This probably belongs in `MasterScheduleManager`

2021-10-03 23:37 UTC, EricSiegNW commented on Psorcast/Psorcast/MeasureTabViewController.swift
> +    let totalStudyWeeks = 12
Waiting on assets for the other resolutions, but didn't think it made sense to wait.

2021-10-04 14:33 UTC, DanWebster requested changes
@EricSiegNW  I'm getting build errors with a missing CLLocationManager, is there an update to SageResearch I need to get from Carthage? 
<img width="1439" alt="Screen Shot 2021-10-04 at 7 31 56 AM" src="https://user-images.githubusercontent.com/3682103/135870351-ce45e7f6-4390-405a-8f38-7eff49788ce1.png">

2021-10-04 15:24 UTC, EricSiegNW commented
Hey Dan,

It did require a change to SageResearch, which has been merged and pointed at. You might need to run update in Carthage to get to that?

2021-10-04 18:21 UTC, merged